//! SWIM membership via foca: node discovery, failure suspicion, and the live
//! member catalog.
//!
//! SWIM provides *hints only* — which nodes exist, their addresses, and
//! whether they look alive. Correctness (group membership, lock state, owner
//! liveness) is always decided by Raft; the membership controller consumes
//! this catalog merely to decide what to reconcile next.
//!
//! Wiring: one task owns the sans-io [`foca::Foca`] instance and socket reads,
//! driving it from received datagrams, scheduled timers, optional manual
//! gossip ticks, and seed-resolution updates. Socket writes and DNS resolution
//! are kept outside the Foca critical path so SWIM timers do not drift behind
//! unrelated I/O. Members are published to a `watch` channel as a map of
//! numeric node id → identity.

use std::collections::{BTreeMap, BinaryHeap};
use std::net::SocketAddr;
use std::num::{NonZeroU32, NonZeroUsize};
use std::sync::atomic::{AtomicU64, AtomicUsize, Ordering};
use std::sync::Arc;
use std::time::Duration;

use bytes::Bytes;
use foca::{BincodeCodec, Foca, NoCustomBroadcast, Timer};
use rand::rngs::StdRng;
use rand::SeedableRng;
use serde::{Deserialize, Serialize};
use tokio::net::UdpSocket;
use tokio::sync::{mpsc, watch};
use tracing::{debug, info, warn};

use crate::raft::types::NodeMeta;

/// SWIM identity: who a node is plus everything peers need to reach it.
/// `incarnation` makes re-joins win address conflicts against stale entries.
///
/// The identity's cluster-wide `Addr` is the **advertised** `ip:port` gossip
/// address (`meta.gossip_addr`): joining works by announcing to a seed's
/// resolved address, and foca only accepts announces whose destination `Addr`
/// matches the receiver's own — an address is the one thing both sides can
/// agree on before they have exchanged identities.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NodeIdentity {
    pub node_id: u64,
    pub meta: NodeMeta,
    pub incarnation: u64,
}

impl foca::Identity for NodeIdentity {
    type Addr = String;

    fn addr(&self) -> String {
        self.meta.gossip_addr.clone()
    }

    fn win_addr_conflict(&self, adversary: &Self) -> bool {
        self.node_id == adversary.node_id && self.incarnation > adversary.incarnation
    }

    fn renew(&self) -> Option<Self> {
        Some(Self {
            node_id: self.node_id,
            meta: self.meta.clone(),
            incarnation: self.incarnation + 1,
        })
    }
}

/// Live cluster members as currently believed by SWIM (self included).
pub type MemberMap = BTreeMap<u64, NodeIdentity>;

#[derive(Clone)]
pub struct ClusterMembers {
    rx: watch::Receiver<MemberMap>,
    local: Arc<std::sync::RwLock<NodeIdentity>>,
    metrics: Arc<GossipMetrics>,
}

impl ClusterMembers {
    /// Subscribe to membership updates.
    pub fn watch(&self) -> watch::Receiver<MemberMap> {
        self.rx.clone()
    }

    /// Current snapshot of live members.
    pub fn snapshot(&self) -> MemberMap {
        self.rx.borrow().clone()
    }

    pub fn local(&self) -> NodeIdentity {
        self.local
            .read()
            .expect("local gossip identity lock poisoned")
            .clone()
    }

    pub fn metrics(&self) -> Arc<GossipMetrics> {
        self.metrics.clone()
    }
}

type FocaInstance =
    Foca<NodeIdentity, BincodeCodec<bincode::config::Configuration>, StdRng, NoCustomBroadcast>;

/// Runtime knobs for the SWIM layer. Defaults follow Foca's LAN profile and
/// keep only the seed-bootstrap cadence in pathlockd.
#[derive(Debug, Clone)]
pub struct GossipOptions {
    /// Expected active members; used by Foca to size dissemination and
    /// suspicion timing.
    pub cluster_size: NonZeroU32,
    /// Maximum UDP payload accepted/generated by Foca.
    pub max_packet_size: NonZeroUsize,
    /// How often DNS seeds are refreshed and announced while this node is
    /// lonely.
    pub seed_announce_interval: Duration,
    /// Optional extra `Foca::gossip()` cadence. `None` relies on Foca's
    /// built-in periodic gossip from the config.
    pub manual_gossip_interval: Option<Duration>,
    /// Whether to keep Foca's periodic announce/gossip timers enabled.
    pub foca_periodic: bool,
    /// Bounded UDP writer queue depth.
    pub send_queue_depth: usize,
}

impl Default for GossipOptions {
    fn default() -> Self {
        Self {
            cluster_size: NonZeroU32::new(32).expect("nonzero"),
            max_packet_size: NonZeroUsize::new(1400).expect("nonzero"),
            seed_announce_interval: Duration::from_secs(5),
            manual_gossip_interval: None,
            foca_periodic: true,
            send_queue_depth: 1024,
        }
    }
}

impl GossipOptions {
    fn foca_config(&self) -> foca::Config {
        let mut config = foca::Config::new_lan(self.cluster_size);
        config.max_packet_size = self.max_packet_size;
        if !self.foca_periodic {
            config.periodic_announce = None;
            config.periodic_announce_to_down_members = None;
            config.periodic_gossip = None;
        }
        config
    }
}

#[derive(Default)]
pub struct GossipMetrics {
    member_count: AtomicUsize,
    timer_backlog: AtomicUsize,
    send_queue_depth: AtomicUsize,
    bad_datagrams: AtomicU64,
    member_up: AtomicU64,
    member_down: AtomicU64,
    renamed: AtomicU64,
    rejoins: AtomicU64,
    idle: AtomicU64,
    send_failures: AtomicU64,
    send_dropped: AtomicU64,
    seed_resolve_failures: AtomicU64,
    unresolved_targets: AtomicU64,
    local_incarnation: AtomicU64,
}

impl GossipMetrics {
    pub fn member_count(&self) -> u64 {
        self.member_count.load(Ordering::Relaxed) as u64
    }
    pub fn timer_backlog(&self) -> u64 {
        self.timer_backlog.load(Ordering::Relaxed) as u64
    }
    pub fn send_queue_depth(&self) -> u64 {
        self.send_queue_depth.load(Ordering::Relaxed) as u64
    }
    pub fn bad_datagrams(&self) -> u64 {
        self.bad_datagrams.load(Ordering::Relaxed)
    }
    pub fn member_up(&self) -> u64 {
        self.member_up.load(Ordering::Relaxed)
    }
    pub fn member_down(&self) -> u64 {
        self.member_down.load(Ordering::Relaxed)
    }
    pub fn renamed(&self) -> u64 {
        self.renamed.load(Ordering::Relaxed)
    }
    pub fn rejoins(&self) -> u64 {
        self.rejoins.load(Ordering::Relaxed)
    }
    pub fn idle(&self) -> u64 {
        self.idle.load(Ordering::Relaxed)
    }
    pub fn send_failures(&self) -> u64 {
        self.send_failures.load(Ordering::Relaxed)
    }
    pub fn send_dropped(&self) -> u64 {
        self.send_dropped.load(Ordering::Relaxed)
    }
    pub fn seed_resolve_failures(&self) -> u64 {
        self.seed_resolve_failures.load(Ordering::Relaxed)
    }
    pub fn unresolved_targets(&self) -> u64 {
        self.unresolved_targets.load(Ordering::Relaxed)
    }
    pub fn local_incarnation(&self) -> u64 {
        self.local_incarnation.load(Ordering::Relaxed)
    }

    fn set_member_count(&self, count: usize) {
        self.member_count.store(count, Ordering::Relaxed);
    }
    fn set_timer_backlog(&self, count: usize) {
        self.timer_backlog.store(count, Ordering::Relaxed);
    }
    fn set_local_incarnation(&self, incarnation: u64) {
        self.local_incarnation.store(incarnation, Ordering::Relaxed);
    }
}

#[derive(Clone)]
struct SeedTarget {
    seed: String,
    addr: SocketAddr,
    target: NodeIdentity,
}

struct OutboundDatagram {
    dest: SocketAddr,
    data: Bytes,
}

/// Start the SWIM layer: bind the UDP socket, join via `seed_nodes`
/// (`host:port` gossip addresses, DNS-resolvable), and publish the member
/// catalog.
pub async fn start_gossip(
    local: NodeIdentity,
    bind_addr: SocketAddr,
    seed_nodes: Vec<String>,
) -> anyhow::Result<ClusterMembers> {
    start_gossip_with_options(local, bind_addr, seed_nodes, GossipOptions::default()).await
}

pub async fn start_gossip_with_options(
    local: NodeIdentity,
    bind_addr: SocketAddr,
    seed_nodes: Vec<String>,
    options: GossipOptions,
) -> anyhow::Result<ClusterMembers> {
    anyhow::ensure!(
        options.send_queue_depth > 0,
        "gossip send_queue_depth must be > 0"
    );
    anyhow::ensure!(
        !options.seed_announce_interval.is_zero(),
        "gossip seed_announce_interval must be > 0"
    );
    if let Some(interval) = options.manual_gossip_interval {
        anyhow::ensure!(
            !interval.is_zero(),
            "gossip manual_gossip_interval must be > 0 when enabled"
        );
    }

    let socket = Arc::new(
        UdpSocket::bind(bind_addr)
            .await
            .map_err(|e| anyhow::anyhow!("binding gossip socket {bind_addr}: {e}"))?,
    );
    info!(%bind_addr, node_id = local.node_id, "gossip listening");

    let mut initial = MemberMap::new();
    initial.insert(local.node_id, local.clone());
    let (tx, rx) = watch::channel(initial);
    let local_state = Arc::new(std::sync::RwLock::new(local.clone()));
    let metrics = Arc::new(GossipMetrics::default());
    metrics.set_member_count(1);
    metrics.set_local_incarnation(local.incarnation);

    let config = options.foca_config();
    let max_packet_size = config.max_packet_size.get();
    let foca: FocaInstance = Foca::new(
        local.clone(),
        config,
        StdRng::from_os_rng(),
        BincodeCodec(bincode::config::standard()),
    );

    let (send_tx, send_rx) = mpsc::channel(options.send_queue_depth);
    tokio::spawn(socket_writer(socket.clone(), send_rx, metrics.clone()));

    let seed_rx = spawn_seed_resolver(
        seed_nodes,
        local.meta.gossip_addr.clone(),
        options.seed_announce_interval,
        metrics.clone(),
    );

    tokio::spawn(gossip_loop(
        foca,
        socket,
        tx,
        local_state.clone(),
        send_tx,
        seed_rx,
        max_packet_size,
        options.manual_gossip_interval,
        metrics.clone(),
    ));

    Ok(ClusterMembers {
        rx,
        local: local_state,
        metrics,
    })
}

/// Resolve a seed's gossip address. The seed's node id and metadata are
/// unknown until it answers, so the announce target is a placeholder identity
/// whose `Addr` (the resolved `ip:port`) matches the seed's advertised
/// address — that match is what makes the seed accept the announce; the real
/// identity arrives with its feed reply. Placeholder ids sit far outside the
/// ordinal range and are filtered from the published catalog.
async fn resolve_seed(seed: &str) -> Option<(SocketAddr, NodeIdentity)> {
    let mut addrs = tokio::net::lookup_host(seed).await.ok()?;
    let addr = addrs.next()?;
    Some((
        addr,
        NodeIdentity {
            node_id: u64::MAX ^ seed_hash(seed),
            meta: NodeMeta {
                name: format!("seed:{seed}"),
                raft_addr: String::new(),
                public_addr: String::new(),
                gossip_addr: addr.to_string(),
            },
            incarnation: 0,
        },
    ))
}

fn seed_hash(seed: &str) -> u64 {
    xxhash_rust::xxh3::xxh3_64(seed.as_bytes()) >> 16
}

/// The address this node advertises in its SWIM identity, raft membership,
/// and event fan-out: explicit override > specified bind IP > auto-detected
/// outbound IP (the UDP-connect trick — no packet is actually sent).
pub fn advertised_addr(
    bind: SocketAddr,
    advertise_override: Option<&str>,
    probe_target: Option<&SocketAddr>,
) -> anyhow::Result<SocketAddr> {
    if let Some(advertised) = advertise_override {
        return advertised
            .parse()
            .map_err(|e| anyhow::anyhow!("advertise addr {advertised}: {e}"));
    }
    if !bind.ip().is_unspecified() {
        return Ok(bind);
    }
    let probe = probe_target
        .copied()
        .unwrap_or_else(|| "8.8.8.8:53".parse().expect("static addr"));
    let sock = std::net::UdpSocket::bind(("0.0.0.0", 0))
        .map_err(|e| anyhow::anyhow!("probing local address: {e}"))?;
    sock.connect(probe)
        .map_err(|e| anyhow::anyhow!("probing local address via {probe}: {e}"))?;
    let local = sock
        .local_addr()
        .map_err(|e| anyhow::anyhow!("probing local address: {e}"))?;
    Ok(SocketAddr::new(local.ip(), bind.port()))
}

struct PendingTimer {
    fire_at: tokio::time::Instant,
    timer: Timer<NodeIdentity>,
    seq: u64,
}

impl PartialEq for PendingTimer {
    fn eq(&self, other: &Self) -> bool {
        self.fire_at == other.fire_at && self.seq == other.seq
    }
}
impl Eq for PendingTimer {}
impl PartialOrd for PendingTimer {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl Ord for PendingTimer {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        // Min-heap by fire time (BinaryHeap is a max-heap).
        other
            .fire_at
            .cmp(&self.fire_at)
            .then(other.seq.cmp(&self.seq))
    }
}

async fn gossip_loop(
    mut foca: FocaInstance,
    socket: Arc<UdpSocket>,
    tx: watch::Sender<MemberMap>,
    local: Arc<std::sync::RwLock<NodeIdentity>>,
    send_tx: mpsc::Sender<OutboundDatagram>,
    mut seed_rx: Option<mpsc::Receiver<Vec<SeedTarget>>>,
    max_packet_size: usize,
    manual_gossip_interval: Option<Duration>,
    metrics: Arc<GossipMetrics>,
) {
    let mut runtime = foca::AccumulatingRuntime::new();
    let mut timers: BinaryHeap<PendingTimer> = BinaryHeap::new();
    let mut timer_seq = 0u64;
    // Gossip-address book for datagram delivery (node id → socket addr).
    let mut addr_book: BTreeMap<u64, SocketAddr> = BTreeMap::new();
    let mut seed_targets: BTreeMap<String, SeedTarget> = BTreeMap::new();

    let mut recv_buf = vec![0u8; max_packet_size];
    let mut gossip_tick = manual_gossip_interval.map(|interval| {
        let mut tick = tokio::time::interval(interval);
        tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
        tick
    });

    loop {
        let next_timer = timers.peek().map(|t| t.fire_at);
        tokio::select! {
            recv = socket.recv_from(&mut recv_buf) => {
                match recv {
                    Ok((len, _from)) => {
                        if let Err(e) = foca.handle_data(&recv_buf[..len], &mut runtime) {
                            metrics.bad_datagrams.fetch_add(1, Ordering::Relaxed);
                            debug!(error = %e, "gossip: bad datagram");
                        }
                    }
                    Err(e) => {
                        warn!(error = %e, "gossip: socket recv failed");
                        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
                    }
                }
            }
            _ = async {
                match next_timer {
                    Some(at) => tokio::time::sleep_until(at).await,
                    None => std::future::pending().await,
                }
            } => {
                let now = tokio::time::Instant::now();
                while let Some(timer) = pop_due_timer(&mut timers, now) {
                    if let Err(e) = foca.handle_timer(timer, &mut runtime) {
                        debug!(error = %e, "gossip: timer handling failed");
                    }
                }
            }
            _ = tick_optional(&mut gossip_tick) => {
                if let Err(e) = foca.gossip(&mut runtime) {
                    debug!(error = %e, "gossip: round failed");
                }
            }
            targets = recv_seed_targets(&mut seed_rx) => {
                for target in targets {
                    addr_book.insert(target.target.node_id, target.addr);
                    seed_targets.insert(target.seed.clone(), target);
                }
                if foca.num_members() <= 1 {
                    for seed in seed_targets.values() {
                        if let Err(e) = foca.announce(seed.target.clone(), &mut runtime) {
                            debug!(seed = %seed.seed, error = %e, "gossip: announce failed");
                        }
                    }
                }
            }
        }

        // Drain the runtime: sends, new timers, notifications.
        while let Some((to, data)) = runtime.to_send() {
            let dest = resolve_member_addr(&to, &mut addr_book);
            if let Some(dest) = dest {
                enqueue_send(&send_tx, dest, data, &metrics);
            } else {
                metrics.unresolved_targets.fetch_add(1, Ordering::Relaxed);
                debug!(node = to.node_id, addr = %to.meta.gossip_addr, "gossip: unresolved send target");
            }
        }
        while let Some((after, timer)) = runtime.to_schedule() {
            timer_seq += 1;
            timers.push(PendingTimer {
                fire_at: tokio::time::Instant::now() + after,
                timer,
                seq: timer_seq,
            });
        }
        metrics.set_timer_backlog(timers.len());
        let mut membership_changed = false;
        while let Some(notification) = runtime.to_notify() {
            membership_changed |= handle_notification(notification, &local, &metrics);
        }
        if membership_changed {
            let mut members: MemberMap = foca
                .iter_members()
                .map(|m| (m.id().node_id, m.id().clone()))
                .filter(|(id, ident)| !is_placeholder(*id, ident))
                .collect();
            let local_identity = local
                .read()
                .expect("local gossip identity lock poisoned")
                .clone();
            members.insert(local_identity.node_id, local_identity);
            for member in members.values() {
                if let Ok(addr) = member.meta.gossip_addr.parse() {
                    addr_book.insert(member.node_id, addr);
                }
            }
            let count = members.len();
            if tx.send(members).is_err() {
                info!("gossip: no subscribers left; stopping");
                return;
            }
            metrics.set_member_count(count);
            debug!(members = count, "gossip: membership updated");
        }
    }
}

fn pop_due_timer(
    timers: &mut BinaryHeap<PendingTimer>,
    now: tokio::time::Instant,
) -> Option<Timer<NodeIdentity>> {
    if timers.peek().is_some_and(|pending| pending.fire_at <= now) {
        timers.pop().map(|pending| pending.timer)
    } else {
        None
    }
}

async fn tick_optional(tick: &mut Option<tokio::time::Interval>) {
    match tick {
        Some(tick) => {
            tick.tick().await;
        }
        None => std::future::pending().await,
    }
}

async fn recv_seed_targets(rx: &mut Option<mpsc::Receiver<Vec<SeedTarget>>>) -> Vec<SeedTarget> {
    let Some(receiver) = rx.as_mut() else {
        return std::future::pending().await;
    };
    match receiver.recv().await {
        Some(targets) => targets,
        None => {
            *rx = None;
            Vec::new()
        }
    }
}

fn handle_notification(
    notification: foca::OwnedNotification<NodeIdentity>,
    local: &Arc<std::sync::RwLock<NodeIdentity>>,
    metrics: &GossipMetrics,
) -> bool {
    use foca::OwnedNotification;
    match notification {
        OwnedNotification::MemberUp(id) => {
            metrics.member_up.fetch_add(1, Ordering::Relaxed);
            info!(node = id.node_id, name = %id.meta.name, "gossip: member up");
            true
        }
        OwnedNotification::MemberDown(id) => {
            metrics.member_down.fetch_add(1, Ordering::Relaxed);
            info!(node = id.node_id, name = %id.meta.name, "gossip: member down");
            true
        }
        OwnedNotification::Rename(old, new) => {
            metrics.renamed.fetch_add(1, Ordering::Relaxed);
            if old.node_id != new.node_id {
                warn!(
                    old_node = old.node_id,
                    new_node = new.node_id,
                    gossip_addr = %new.meta.gossip_addr,
                    "gossip: identity changed node id for the same address"
                );
            } else {
                debug!(
                    node = new.node_id,
                    old_inc = old.incarnation,
                    new_inc = new.incarnation,
                    "gossip: member renamed"
                );
            }
            true
        }
        OwnedNotification::Rejoin(new_identity) => {
            metrics.rejoins.fetch_add(1, Ordering::Relaxed);
            metrics.set_local_incarnation(new_identity.incarnation);
            *local.write().expect("local gossip identity lock poisoned") = new_identity.clone();
            info!(
                node = new_identity.node_id,
                incarnation = new_identity.incarnation,
                "gossip: rejoined with renewed identity"
            );
            true
        }
        OwnedNotification::Idle => {
            metrics.idle.fetch_add(1, Ordering::Relaxed);
            debug!("gossip: cluster idle");
            true
        }
        OwnedNotification::Active => {
            debug!("gossip: cluster active");
            false
        }
        OwnedNotification::Defunct => {
            warn!("gossip: local identity declared defunct");
            false
        }
    }
}

fn spawn_seed_resolver(
    seed_nodes: Vec<String>,
    local_gossip_addr: String,
    interval: Duration,
    metrics: Arc<GossipMetrics>,
) -> Option<mpsc::Receiver<Vec<SeedTarget>>> {
    if seed_nodes.is_empty() {
        return None;
    }
    let (tx, rx) = mpsc::channel(1);
    tokio::spawn(async move {
        let mut tick = tokio::time::interval(interval);
        tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
        loop {
            tick.tick().await;
            let mut targets = Vec::new();
            for seed in &seed_nodes {
                match resolve_seed(seed).await {
                    Some((addr, target)) if addr.to_string() != local_gossip_addr => {
                        targets.push(SeedTarget {
                            seed: seed.clone(),
                            addr,
                            target,
                        });
                    }
                    Some(_) => {}
                    None => {
                        metrics
                            .seed_resolve_failures
                            .fetch_add(1, Ordering::Relaxed);
                        debug!(%seed, "gossip: seed resolve failed");
                    }
                }
            }
            if tx.send(targets).await.is_err() {
                return;
            }
        }
    });
    Some(rx)
}

async fn socket_writer(
    socket: Arc<UdpSocket>,
    mut rx: mpsc::Receiver<OutboundDatagram>,
    metrics: Arc<GossipMetrics>,
) {
    while let Some(datagram) = rx.recv().await {
        metrics.send_queue_depth.fetch_sub(1, Ordering::Relaxed);
        if let Err(e) = socket.send_to(&datagram.data, datagram.dest).await {
            metrics.send_failures.fetch_add(1, Ordering::Relaxed);
            debug!(to = %datagram.dest, error = %e, "gossip: send failed");
        }
    }
}

fn enqueue_send(
    send_tx: &mpsc::Sender<OutboundDatagram>,
    dest: SocketAddr,
    data: Bytes,
    metrics: &GossipMetrics,
) {
    metrics.send_queue_depth.fetch_add(1, Ordering::Relaxed);
    match send_tx.try_send(OutboundDatagram { dest, data }) {
        Ok(()) => {}
        Err(tokio::sync::mpsc::error::TrySendError::Full(_)) => {
            metrics.send_queue_depth.fetch_sub(1, Ordering::Relaxed);
            metrics.send_dropped.fetch_add(1, Ordering::Relaxed);
            debug!(to = %dest, "gossip: dropping outbound datagram; send queue full");
        }
        Err(tokio::sync::mpsc::error::TrySendError::Closed(_)) => {
            metrics.send_queue_depth.fetch_sub(1, Ordering::Relaxed);
            metrics.send_dropped.fetch_add(1, Ordering::Relaxed);
            debug!(to = %dest, "gossip: dropping outbound datagram; writer closed");
        }
    }
}

fn is_placeholder(id: u64, ident: &NodeIdentity) -> bool {
    // Seed placeholders carry no raft address and ids far outside the
    // ordinal range.
    id > u32::MAX as u64 && ident.meta.raft_addr.is_empty()
}

fn resolve_member_addr(
    to: &NodeIdentity,
    addr_book: &mut BTreeMap<u64, SocketAddr>,
) -> Option<SocketAddr> {
    if let Ok(addr) = to.meta.gossip_addr.parse() {
        addr_book.insert(to.node_id, addr);
        return Some(addr);
    }
    // Placeholder identities (seeds) resolve via DNS once and are cached.
    if let Some(addr) = addr_book.get(&to.node_id) {
        return Some(*addr);
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use foca::Identity;

    fn identity(node_id: u64, incarnation: u64) -> NodeIdentity {
        NodeIdentity {
            node_id,
            meta: NodeMeta {
                name: format!("pathlockd-{node_id}"),
                raft_addr: format!("http://10.0.0.{node_id}:50052"),
                public_addr: format!("http://10.0.0.{node_id}:50051"),
                gossip_addr: format!("10.0.0.{node_id}:7946"),
            },
            incarnation,
        }
    }

    fn test_options() -> GossipOptions {
        GossipOptions {
            seed_announce_interval: Duration::from_millis(50),
            send_queue_depth: 64,
            ..GossipOptions::default()
        }
    }

    async fn free_local_addr() -> SocketAddr {
        let sock = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let addr = sock.local_addr().unwrap();
        drop(sock);
        addr
    }

    async fn wait_until(mut condition: impl FnMut() -> bool) -> bool {
        tokio::time::timeout(Duration::from_secs(5), async {
            loop {
                if condition() {
                    return true;
                }
                tokio::time::sleep(Duration::from_millis(10)).await;
            }
        })
        .await
        .unwrap_or(false)
    }

    #[test]
    fn identity_renewal_bumps_incarnation_and_wins_conflicts() {
        let old = identity(3, 0);
        let renewed = old.renew().expect("renewable");
        assert_eq!(renewed.node_id, old.node_id);
        assert_eq!(renewed.incarnation, 1);
        assert!(renewed.win_addr_conflict(&old));
        assert!(!old.win_addr_conflict(&renewed));
    }

    #[test]
    fn identity_conflict_requires_same_node_id() {
        let old = identity(3, 0);
        let mut different_node = identity(4, 9);
        different_node.meta.gossip_addr = old.meta.gossip_addr.clone();

        assert!(!different_node.win_addr_conflict(&old));
    }

    #[test]
    fn rejoin_notification_updates_local_identity() {
        let old = identity(3, 0);
        let renewed = old.renew().expect("renewable");
        let local = Arc::new(std::sync::RwLock::new(old));
        let metrics = GossipMetrics::default();

        assert!(handle_notification(
            foca::OwnedNotification::Rejoin(renewed.clone()),
            &local,
            &metrics,
        ));
        assert_eq!(
            local.read().unwrap().incarnation,
            renewed.incarnation,
            "local identity must track Foca's renewed identity"
        );
        assert_eq!(metrics.rejoins(), 1);
        assert_eq!(metrics.local_incarnation(), renewed.incarnation);
    }

    #[test]
    fn options_drive_foca_packet_and_periodic_settings() {
        let options = GossipOptions {
            max_packet_size: NonZeroUsize::new(2048).unwrap(),
            foca_periodic: false,
            ..GossipOptions::default()
        };
        let config = options.foca_config();

        assert_eq!(config.max_packet_size.get(), 2048);
        assert!(config.periodic_announce.is_none());
        assert!(config.periodic_announce_to_down_members.is_none());
        assert!(config.periodic_gossip.is_none());
    }

    #[test]
    fn due_timers_are_drained_in_deadline_order() {
        let now = tokio::time::Instant::now();
        let later = now + Duration::from_secs(1);
        let mut timers = BinaryHeap::new();
        let first = Timer::RemoveDown(identity(1, 0));
        let second = Timer::RemoveDown(identity(2, 0));
        let future = Timer::RemoveDown(identity(3, 0));

        timers.push(PendingTimer {
            fire_at: now,
            timer: second.clone(),
            seq: 2,
        });
        timers.push(PendingTimer {
            fire_at: now,
            timer: first.clone(),
            seq: 1,
        });
        timers.push(PendingTimer {
            fire_at: later,
            timer: future,
            seq: 3,
        });

        let mut popped = Vec::new();
        while let Some(timer) = pop_due_timer(&mut timers, now) {
            popped.push(timer);
        }

        assert_eq!(popped, vec![first, second]);
        assert_eq!(timers.len(), 1);
    }

    #[tokio::test]
    async fn two_nodes_discover_each_other() {
        let addr_a = free_local_addr().await;
        let addr_b = free_local_addr().await;
        let unused_seed = free_local_addr().await;
        let mut id_a = identity(1, 0);
        id_a.meta.gossip_addr = addr_a.to_string();
        let mut id_b = identity(2, 0);
        id_b.meta.gossip_addr = addr_b.to_string();

        let members_a = start_gossip_with_options(id_a, addr_a, vec![], test_options())
            .await
            .unwrap();
        let members_b = start_gossip_with_options(
            id_b,
            addr_b,
            vec![unused_seed.to_string(), addr_a.to_string()],
            test_options(),
        )
        .await
        .unwrap();

        let mut rx = members_b.watch();
        let found = tokio::time::timeout(Duration::from_secs(5), async {
            loop {
                if rx.borrow().len() >= 2 {
                    return true;
                }
                if rx.changed().await.is_err() {
                    return false;
                }
            }
        })
        .await
        .unwrap_or(false);
        assert!(found, "node B must discover node A via the seed announce");
        // A also learns about B.
        let mut rx_a = members_a.watch();
        let found_a = tokio::time::timeout(Duration::from_secs(5), async {
            loop {
                if rx_a.borrow().len() >= 2 {
                    return true;
                }
                if rx_a.changed().await.is_err() {
                    return false;
                }
            }
        })
        .await
        .unwrap_or(false);
        assert!(found_a, "node A must learn about node B");
    }

    #[tokio::test]
    async fn malformed_datagrams_are_counted() {
        let addr = free_local_addr().await;
        let mut id = identity(1, 0);
        id.meta.gossip_addr = addr.to_string();
        let members = start_gossip_with_options(id, addr, vec![], test_options())
            .await
            .unwrap();

        let sender = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        sender.send_to(b"not-a-foca-packet", addr).await.unwrap();

        assert!(
            wait_until(|| members.metrics().bad_datagrams() > 0).await,
            "bad datagram counter should advance"
        );
    }
}
